# -*- coding: utf-8 -*-
"""Regressor.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1tJrhyRKo6q7jnqpdnoRAnHDsIKVYZCNT
"""

import pandas as pd
import numpy as np
import joblib
# from sklearn.linear_model import LinearRegression
# from sklearn.ensemble import VotingRegressor
# from sklearn.ensemble import RandomForestRegressor
# import xgboost as xgb
# from xgboost import XGBRegressor
# from sklearn.metrics import accuracy_score,r2_score,mean_squared_error
from winddirectionprediction import predict_wind_direction_main
from windspeedprediction import predict_wind_speed_main

def predict_power():
	predict_wind_direction_main()
	predict_wind_speed_main()
	df = pd.read_csv('Future_Data.csv', index_col="Index")
	del df['Unnamed: 0']
	del df['Unnamed: 0.1']
	del df['LV ActivePower (kW)']
	print(df.head())

	regressor = joblib.load('ML_Model.pkl')

	predictions = regressor.predict(df)

	predictions.shape

	df = pd.read_csv('Future_Data.csv')
	df['LV ActivePower (kW)'] = predictions
	df.to_csv('Future_Data.csv')


predict_power()
